<a href="https://colab.research.google.com/github/Adyan213/Hands-On-ML/blob/main/Chapter_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import make_moons

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.ensemble import VotingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [ ]:
X, y= make_moons(n_samples=500, noise=0.3, random_state=42)
X_train, X_test, y_train, y_test= train_test_split(X, y, random_state=42)
voting_clf=VotingClassifier(
    estimators=[
        ('lr', LogisticRegression(random_state=42)),
        ('rf', RandomForestClassifier(random_state=42)),
        ('svc', SVC(random_state=42))
    ]
)
voting_clf.fit(X_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=42)),
                             ('rf', RandomForestClassifier(random_state=42)),
                             ('svc', SVC(random_state=42))])

In [ ]:
for name, clf in voting_clf.named_estimators_.items():
  print(name,'=',clf.score(X_test, y_test))

lr = 0.864
rf = 0.896
svc = 0.896


In [ ]:
voting_clf.predict(X_test[:1])

array([1])

In [ ]:
[clf.predict(X_test[:1]) for clf in voting_clf.estimators_]

[array([1]), array([1]), array([0])]

In [ ]:
voting_clf.score(X_test, y_test)

0.912

In [ ]:
voting_clf.voting='soft'
voting_clf.named_estimators['svc'].probability=True
voting_clf.fit(X_test, y_test)
voting_clf.score(X_test, y_test)

0.928

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

bag_clf=BaggingClassifier(
    DecisionTreeClassifier(), n_estimators=500,
    max_samples=100, n_jobs=-1, bootstrap=False
)
bag_clf.fit(X_train, y_train)
bag_clf.score(X_test, y_test)

0.912

In [ ]:
bag_clf=BaggingClassifier(
    DecisionTreeClassifier(), n_estimators=500,
    oob_score=True, n_jobs=-1, bootstrap=True
)
bag_clf.fit(X_train, y_train)
bag_clf.oob_score_

0.9013333333333333

In [ ]:
from sklearn.metrics import accuracy_score
y_pred=bag_clf.predict(X_test)
accuracy_score(y_test, y_pred)

0.92

In [ ]:
bag_clf.oob_decision_function_[:3]

array([[0.41477273, 0.58522727],
       [0.39344262, 0.60655738],
       [1.        , 0.        ]])

In [ ]:
print(1-(1-1/67)**67)

0.6348831294723861


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [ ]:
rnd_clf=RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, n_jobs=-1, random_state=42)
rnd_clf.fit(X_train, y_train)
y_pred_rf=rnd_clf.predict(X_test)

In [ ]:
cross_val_score(rnd_clf, X_train, y_train, cv=10)

array([0.94736842, 0.89473684, 0.94736842, 0.94736842, 0.86842105,
       0.89189189, 0.94594595, 0.94594595, 0.89189189, 0.89189189])

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier

In [ ]:
ex_clf=ExtraTreesClassifier(n_estimators=500, max_leaf_nodes=16, n_jobs=-1, random_state=42)
ex_clf.fit(X_train, y_train)
y_pred_ex=ex_clf.predict(X_test)
cross_val_score(ex_clf, X_train, y_train, cv=10)

array([0.92105263, 0.89473684, 0.86842105, 0.89473684, 0.86842105,
       0.86486486, 0.91891892, 0.97297297, 0.86486486, 0.91891892])

In [ ]:
from sklearn.datasets import load_iris
iris=load_iris(as_frame=True)
rnd_clf=RandomForestClassifier(n_estimators=500, random_state=42)
rnd_clf.fit(iris.data, iris.target)
for score, name in zip(rnd_clf.feature_importances_, iris.data.columns):
  print(score, name)

0.11249225099876375 sepal length (cm)
0.02311928828251033 sepal width (cm)
0.4410304643639577 petal length (cm)
0.4233579963547682 petal width (cm)


In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
ada_clf=AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=1), n_estimators=30,
    learning_rate=0.5, random_state=42
)
ada_clf.fit(X_train, y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   learning_rate=0.5, n_estimators=30, random_state=42)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, ada_clf.predict(X_test))

0.88

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
import numpy as np

In [ ]:
np.random.seed(42)
X=np.random.rand(100, 1)-0.5
y=3*X[:, 0]**2+0.05*np.random.randn(100)

In [ ]:
tree_reg1=DecisionTreeRegressor(max_depth=2, random_state=42)
tree_reg1.fit(X, y)

DecisionTreeRegressor(max_depth=2, random_state=42)

In [ ]:
y2=y-tree_reg1.predict(X)
tree_reg2=DecisionTreeRegressor(max_depth=2, random_state=42)
tree_reg2.fit(X, y2)

DecisionTreeRegressor(max_depth=2, random_state=42)

In [ ]:
y3=y2-tree_reg2.predict(X)
tree_reg3=DecisionTreeRegressor(max_depth=2, random_state=42)
tree_reg3.fit(X, y3)

DecisionTreeRegressor(max_depth=2, random_state=42)

In [ ]:
X_new=np.array([[-0.4], [0], [0.5]])
sum(tree.predict(X_new) for tree in (tree_reg1, tree_reg2, tree_reg3))

array([0.49484029, 0.04021166, 0.75026781])

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
gbrt=GradientBoostingRegressor(max_depth=2, n_estimators=3, learning_rate=1.0, random_state=42)
gbrt.fit(X, y)

GradientBoostingRegressor(learning_rate=1.0, max_depth=2, n_estimators=3,
                          random_state=42)

In [ ]:
gbrt.predict(X_new)

array([0.49484029, 0.04021166, 0.75026781])

In [ ]:
gbrt_best=GradientBoostingRegressor(max_depth=2, learning_rate=0.05, n_estimators=120, n_iter_no_change=10, random_state=42)
gbrt_best.fit(X, y)

GradientBoostingRegressor(learning_rate=0.05, max_depth=2, n_estimators=120,
                          n_iter_no_change=10, random_state=42)

In [ ]:
gbrt_best.predict(X_new)

array([0.52558815, 0.00916826, 0.70597796])

In [ ]:
gbrt_best.n_estimators_

92

In [ ]:
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.datasets import fetch_california_housing

In [ ]:
housing=fetch_california_housing(as_frame=True)
housing_data=housing.frame.drop("MedHouseVal", axis=1)
housing_labels=housing.frame["MedHouseVal"]

In [ ]:
hgb_reg=make_pipeline(
    HistGradientBoostingRegressor(random_state=42)
)
hgb_reg.fit(housing_data, housing_labels)

Pipeline(steps=[('histgradientboostingregressor',
                 HistGradientBoostingRegressor(random_state=42))])

In [ ]:
from sklearn.model_selection import cross_val_score
import pandas as pd

hgb_rmses = -cross_val_score(hgb_reg, housing_data, housing_labels,
                             scoring="neg_root_mean_squared_error", cv=10)
pd.Series(hgb_rmses).describe()

,0
count,10.000000
mean,0.583789
std,0.129148
min,0.419033
25%,0.474240
50%,0.587174
75%,0.658305
max,0.808038


In [ ]:
from sklearn.ensemble import StackingClassifier

stack_clf=StackingClassifier(
    estimators=[
        ('lr', LogisticRegression(random_state=42)),
        ('rf', RandomForestClassifier(random_state=42)),
        ('svc', SVC(probability=True, random_state=42))
    ],
    final_estimator=RandomForestClassifier(random_state=43),
    cv=5
)
stack_clf.fit(X_train, y_train)
stack_clf.score(X_test, y_test)

0.928

In [ ]:
from sklearn.datasets import fetch_openml
X_mnist, y_mnist=fetch_openml('mnist_784', return_X_y=True, as_frame=False, parser='auto')

In [ ]:
y_mnist.shape

(70000,)

In [ ]:
X_train, y_train=X_mnist[:50_000], y_mnist[:50_000]
X_valid, y_valid=X_mnist[50_000:60_000], y_mnist[50_000:60_000]
X_test, y_test=X_mnist[60_000:], y_mnist[60_000:]

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.svm import LinearSVC
from sklearn.neural_network import MLPClassifier

In [ ]:
random_forest_clf=RandomForestClassifier(n_estimators=100, random_state=42)
extra_trees_clf=ExtraTreesClassifier(n_estimators=100, random_state=42)
svm_clf=LinearSVC(max_iter=100, tol=20, dual=True, random_state=42)
mlp_clf=MLPClassifier(random_state=42)

In [ ]:
estimators=[random_forest_clf, extra_trees_clf, svm_clf, mlp_clf]
for estimator in estimators:
  print("Training the", estimator)
  estimator.fit(X_train, y_train)

Training the RandomForestClassifier(random_state=42)
Training the ExtraTreesClassifier(random_state=42)
Training the LinearSVC(dual=True, max_iter=100, random_state=42, tol=20)
Training the MLPClassifier(random_state=42)


In [ ]:
[estimator.score(X_valid, y_valid) for estimator in estimators]

[0.9736, 0.9743, 0.8662, 0.9613]

In [ ]:
from sklearn.ensemble import VotingClassifier

In [ ]:
named_estimators=[
    ("random_forest_clf", random_forest_clf),
    ("extra_trees_clf", extra_trees_clf),
    ("svm_clf", svm_clf),
    ("mlp_clf", mlp_clf)
]

In [ ]:
voting_clf=VotingClassifier(named_estimators)
voting_clf.fit(X_train, y_train)

VotingClassifier(estimators=[('random_forest_clf',
                              RandomForestClassifier(random_state=42)),
                             ('extra_trees_clf',
                              ExtraTreesClassifier(random_state=42)),
                             ('svm_clf',
                              LinearSVC(dual=True, max_iter=100,
                                        random_state=42, tol=20)),
                             ('mlp_clf', MLPClassifier(random_state=42))])

In [ ]:
voting_clf.score(X_valid, y_valid)

0.975

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()
y_valid_encoded=encoder.fit(y_valid)

In [ ]:
y_valid_encoded=y_valid.astype(np.int64)

In [ ]:
[estimator.score(X_valid, y_valid_encoded) for estimator in voting_clf.estimators_]

[0.9736, 0.9743, 0.8662, 0.9613]

In [ ]:
voting_clf.set_params(svm_clf="drop")

VotingClassifier(estimators=[('random_forest_clf',
                              RandomForestClassifier(random_state=42)),
                             ('extra_trees_clf',
                              ExtraTreesClassifier(random_state=42)),
                             ('svm_clf', 'drop'),
                             ('mlp_clf', MLPClassifier(random_state=42))])

In [ ]:
voting_clf.named_estimators_

{'random_forest_clf': RandomForestClassifier(random_state=42),
 'extra_trees_clf': ExtraTreesClassifier(random_state=42),
 'svm_clf': LinearSVC(dual=True, max_iter=100, random_state=42, tol=20),
 'mlp_clf': MLPClassifier(random_state=42)}

In [ ]:
svm_clf_trained=voting_clf.named_estimators_.pop("svm_clf")
voting_clf.estimators_.remove(svm_clf_trained)

In [ ]:
voting_clf.score(X_valid, y_valid)

0.9761

In [ ]:
voting_clf.score(X_test, y_test)

0.9733

In [ ]:
[estimator.score(X_test, y_test.astype(np.int64)) for estimator in voting_clf.estimators_]

[0.968, 0.9703, 0.9618]

In [ ]:
X_valid_predictions=np.empty((len(X_valid), len(estimators)), dtype=object)

for index, estimator in enumerate(estimators):
  X_valid_predictions[:, index]=estimator.predict(X_valid)

In [ ]:
X_valid_predictions

array([['3', '3', '3', '3'],
       ['8', '8', '8', '8'],
       ['6', '6', '6', '6'],
       ...,
       ['5', '5', '5', '5'],
       ['6', '6', '6', '6'],
       ['8', '8', '8', '8']], dtype=object)

In [ ]:
rnd_forest_blender=RandomForestClassifier(n_estimators=200, oob_score=True,
                                          random_state=42)
rnd_forest_blender.fit(X_valid_predictions, y_valid)

RandomForestClassifier(n_estimators=200, oob_score=True, random_state=42)

In [ ]:
rnd_forest_blender.oob_score_

0.9738

In [ ]:
X_test_predictions=np.empty((len(X_test), len(estimators)), dtype=object)

for index, estimator in enumerate(estimators):
  X_test_predictions[:, index]=estimator.predict(X_test)

In [ ]:
y_pred=rnd_forest_blender.predict(X_test_predictions)

In [ ]:
accuracy_score(y_test, y_pred)

0.9688

In [ ]:
X_train_full, y_train_full=X_mnist[:60_000], y_mnist[:60_000]

In [ ]:
stack_clf=StackingClassifier(named_estimators, final_estimator=rnd_forest_blender)
stack_clf.fit(X_train_full, y_train_full)

StackingClassifier(estimators=[('random_forest_clf',
                                RandomForestClassifier(random_state=42)),
                               ('extra_trees_clf',
                                ExtraTreesClassifier(random_state=42)),
                               ('svm_clf',
                                LinearSVC(dual=True, max_iter=100,
                                          random_state=42, tol=20)),
                               ('mlp_clf', MLPClassifier(random_state=42))],
                   final_estimator=RandomForestClassifier(n_estimators=200,
                                                          oob_score=True,
                                                          random_state=42))

In [79]:
stack_clf.score(X_test, y_test)

0.9795